export const SUDAN_STATES = [
  { value: 'الخرطوم',        emoji: '🏙️' },
  { value: 'الجزيرة',        emoji: '🌾' },
  { value: 'النيل الأبيض',   emoji: '💧' },
  { value: 'النيل الأزرق',   emoji: '🌊' },
  { value: 'نهر النيل',      emoji: '🏞️' },
  { value: 'الشمالية',       emoji: '🏜️' },
  { value: 'كسلا',           emoji: '🌄' },
  { value: 'البحر الأحمر',   emoji: '🌊' },
  { value: 'القضارف',        emoji: '🌿' },
  { value: 'سنار',           emoji: '🌳' },
  { value: 'شمال كردفان',    emoji: '⛺' },
  { value: 'جنوب كردفان',    emoji: '🏔️' },
  { value: 'غرب كردفان',     emoji: '🐪' },
  { value: 'شمال دارفور',    emoji: '🏜️' },
  { value: 'جنوب دارفور',    emoji: '🌅' },
  { value: 'شرق دارفور',     emoji: '🌄' },
  { value: 'غرب دارفور',     emoji: '🏕️' },
  { value: 'وسط دارفور',     emoji: '🌾' },
];
